spring:
  datasource:
    url: 'jdbc:h2:mem:AZ;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE'
    username: sa
    password:
    driver-class-name: org.h2.Driver
    continue-on-error: true
    platform: h2
  h2:
    console:
      enabled: false
      path: /h2-console
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
    generate-ddl: false
    database: h2