spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    database: POSTGRESQL
    show-sql: false
    hibernate:
      ddl-auto: none
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/springbootdb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    continue-on-error: true